name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - '4-ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-ticketing
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && docker build -t jasoncrout/ticketing-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jasoncrout/ticketing-auth