name: tests-payments

on:
  pull_request:
    paths:
      - "4-ticketing/payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-ticketing
    steps:
      - uses: actions/checkout@v3
      - run: cd payments && npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
