name: tests-tickets

on:
  pull_request:
    paths:
      - "4-ticketing/tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-ticketing
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
